// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginMessage.proto

package BaseballProtocol;

public final class LoginMessage {
  private LoginMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code BaseballProtocol.PacketType}
   */
  public enum PacketType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CLS_LOGIN_REQUEST = 0;</code>
     */
    CLS_LOGIN_REQUEST(0, 0),
    /**
     * <code>LSC_LOGIN_SUCCESS = 1;</code>
     */
    LSC_LOGIN_SUCCESS(1, 1),
    /**
     * <code>LSC_LOGIN_FAILED = 2;</code>
     */
    LSC_LOGIN_FAILED(2, 2),
    /**
     * <code>CLS_ACCOUNT_CREATE = 3;</code>
     */
    CLS_ACCOUNT_CREATE(3, 3),
    /**
     * <code>LSC_ACCOUNT_CREATE_SUCCESS = 4;</code>
     */
    LSC_ACCOUNT_CREATE_SUCCESS(4, 4),
    /**
     * <code>LSC_ACCOUNT_CREATE_FAILED = 5;</code>
     */
    LSC_ACCOUNT_CREATE_FAILED(5, 5),
    ;

    /**
     * <code>CLS_LOGIN_REQUEST = 0;</code>
     */
    public static final int CLS_LOGIN_REQUEST_VALUE = 0;
    /**
     * <code>LSC_LOGIN_SUCCESS = 1;</code>
     */
    public static final int LSC_LOGIN_SUCCESS_VALUE = 1;
    /**
     * <code>LSC_LOGIN_FAILED = 2;</code>
     */
    public static final int LSC_LOGIN_FAILED_VALUE = 2;
    /**
     * <code>CLS_ACCOUNT_CREATE = 3;</code>
     */
    public static final int CLS_ACCOUNT_CREATE_VALUE = 3;
    /**
     * <code>LSC_ACCOUNT_CREATE_SUCCESS = 4;</code>
     */
    public static final int LSC_ACCOUNT_CREATE_SUCCESS_VALUE = 4;
    /**
     * <code>LSC_ACCOUNT_CREATE_FAILED = 5;</code>
     */
    public static final int LSC_ACCOUNT_CREATE_FAILED_VALUE = 5;


    public final int getNumber() { return value; }

    public static PacketType valueOf(int value) {
      switch (value) {
        case 0: return CLS_LOGIN_REQUEST;
        case 1: return LSC_LOGIN_SUCCESS;
        case 2: return LSC_LOGIN_FAILED;
        case 3: return CLS_ACCOUNT_CREATE;
        case 4: return LSC_ACCOUNT_CREATE_SUCCESS;
        case 5: return LSC_ACCOUNT_CREATE_FAILED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PacketType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<PacketType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PacketType>() {
            public PacketType findValueByNumber(int number) {
              return PacketType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return BaseballProtocol.LoginMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final PacketType[] VALUES = values();

    public static PacketType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private PacketType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:BaseballProtocol.PacketType)
  }

  /**
   * Protobuf enum {@code BaseballProtocol.FailSignal}
   */
  public enum FailSignal
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NO_EXIST = 0;</code>
     */
    NO_EXIST(0, 0),
    /**
     * <code>ALREADY_EXIST = 1;</code>
     */
    ALREADY_EXIST(1, 1),
    /**
     * <code>WRONG_PASSWORD = 2;</code>
     */
    WRONG_PASSWORD(2, 2),
    ;

    /**
     * <code>NO_EXIST = 0;</code>
     */
    public static final int NO_EXIST_VALUE = 0;
    /**
     * <code>ALREADY_EXIST = 1;</code>
     */
    public static final int ALREADY_EXIST_VALUE = 1;
    /**
     * <code>WRONG_PASSWORD = 2;</code>
     */
    public static final int WRONG_PASSWORD_VALUE = 2;


    public final int getNumber() { return value; }

    public static FailSignal valueOf(int value) {
      switch (value) {
        case 0: return NO_EXIST;
        case 1: return ALREADY_EXIST;
        case 2: return WRONG_PASSWORD;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FailSignal>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<FailSignal>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FailSignal>() {
            public FailSignal findValueByNumber(int number) {
              return FailSignal.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return BaseballProtocol.LoginMessage.getDescriptor().getEnumTypes().get(1);
    }

    private static final FailSignal[] VALUES = values();

    public static FailSignal valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private FailSignal(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:BaseballProtocol.FailSignal)
  }

  public interface CLS_login_requestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BaseballProtocol.CLS_login_request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional string password = 2;</code>
     */
    boolean hasPassword();
    /**
     * <code>optional string password = 2;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>optional string password = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code BaseballProtocol.CLS_login_request}
   */
  public static final class CLS_login_request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BaseballProtocol.CLS_login_request)
      CLS_login_requestOrBuilder {
    // Use CLS_login_request.newBuilder() to construct.
    private CLS_login_request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CLS_login_request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CLS_login_request defaultInstance;
    public static CLS_login_request getDefaultInstance() {
      return defaultInstance;
    }

    public CLS_login_request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CLS_login_request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              password_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BaseballProtocol.LoginMessage.internal_static_BaseballProtocol_CLS_login_request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BaseballProtocol.LoginMessage.internal_static_BaseballProtocol_CLS_login_request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BaseballProtocol.LoginMessage.CLS_login_request.class, BaseballProtocol.LoginMessage.CLS_login_request.Builder.class);
    }

    public static com.google.protobuf.Parser<CLS_login_request> PARSER =
        new com.google.protobuf.AbstractParser<CLS_login_request>() {
      public CLS_login_request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CLS_login_request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CLS_login_request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>optional string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private java.lang.Object password_;
    /**
     * <code>optional string password = 2;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string password = 2;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string password = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = "";
      password_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswordBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswordBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static BaseballProtocol.LoginMessage.CLS_login_request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BaseballProtocol.LoginMessage.CLS_login_request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BaseballProtocol.LoginMessage.CLS_login_request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BaseballProtocol.LoginMessage.CLS_login_request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BaseballProtocol.LoginMessage.CLS_login_request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static BaseballProtocol.LoginMessage.CLS_login_request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static BaseballProtocol.LoginMessage.CLS_login_request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static BaseballProtocol.LoginMessage.CLS_login_request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static BaseballProtocol.LoginMessage.CLS_login_request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static BaseballProtocol.LoginMessage.CLS_login_request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(BaseballProtocol.LoginMessage.CLS_login_request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BaseballProtocol.CLS_login_request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BaseballProtocol.CLS_login_request)
        BaseballProtocol.LoginMessage.CLS_login_requestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BaseballProtocol.LoginMessage.internal_static_BaseballProtocol_CLS_login_request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BaseballProtocol.LoginMessage.internal_static_BaseballProtocol_CLS_login_request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BaseballProtocol.LoginMessage.CLS_login_request.class, BaseballProtocol.LoginMessage.CLS_login_request.Builder.class);
      }

      // Construct using BaseballProtocol.LoginMessage.CLS_login_request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BaseballProtocol.LoginMessage.internal_static_BaseballProtocol_CLS_login_request_descriptor;
      }

      public BaseballProtocol.LoginMessage.CLS_login_request getDefaultInstanceForType() {
        return BaseballProtocol.LoginMessage.CLS_login_request.getDefaultInstance();
      }

      public BaseballProtocol.LoginMessage.CLS_login_request build() {
        BaseballProtocol.LoginMessage.CLS_login_request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public BaseballProtocol.LoginMessage.CLS_login_request buildPartial() {
        BaseballProtocol.LoginMessage.CLS_login_request result = new BaseballProtocol.LoginMessage.CLS_login_request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BaseballProtocol.LoginMessage.CLS_login_request) {
          return mergeFrom((BaseballProtocol.LoginMessage.CLS_login_request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BaseballProtocol.LoginMessage.CLS_login_request other) {
        if (other == BaseballProtocol.LoginMessage.CLS_login_request.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000002;
          password_ = other.password_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BaseballProtocol.LoginMessage.CLS_login_request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BaseballProtocol.LoginMessage.CLS_login_request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>optional string password = 2;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            password_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BaseballProtocol.CLS_login_request)
    }

    static {
      defaultInstance = new CLS_login_request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BaseballProtocol.CLS_login_request)
  }

  public interface LSC_login_resultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BaseballProtocol.LSC_login_result)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .BaseballProtocol.FailSignal failsignal = 1;</code>
     */
    boolean hasFailsignal();
    /**
     * <code>optional .BaseballProtocol.FailSignal failsignal = 1;</code>
     */
    BaseballProtocol.LoginMessage.FailSignal getFailsignal();
  }
  /**
   * Protobuf type {@code BaseballProtocol.LSC_login_result}
   */
  public static final class LSC_login_result extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BaseballProtocol.LSC_login_result)
      LSC_login_resultOrBuilder {
    // Use LSC_login_result.newBuilder() to construct.
    private LSC_login_result(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LSC_login_result(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LSC_login_result defaultInstance;
    public static LSC_login_result getDefaultInstance() {
      return defaultInstance;
    }

    public LSC_login_result getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LSC_login_result(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              BaseballProtocol.LoginMessage.FailSignal value = BaseballProtocol.LoginMessage.FailSignal.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                failsignal_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BaseballProtocol.LoginMessage.internal_static_BaseballProtocol_LSC_login_result_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BaseballProtocol.LoginMessage.internal_static_BaseballProtocol_LSC_login_result_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BaseballProtocol.LoginMessage.LSC_login_result.class, BaseballProtocol.LoginMessage.LSC_login_result.Builder.class);
    }

    public static com.google.protobuf.Parser<LSC_login_result> PARSER =
        new com.google.protobuf.AbstractParser<LSC_login_result>() {
      public LSC_login_result parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LSC_login_result(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LSC_login_result> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int FAILSIGNAL_FIELD_NUMBER = 1;
    private BaseballProtocol.LoginMessage.FailSignal failsignal_;
    /**
     * <code>optional .BaseballProtocol.FailSignal failsignal = 1;</code>
     */
    public boolean hasFailsignal() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .BaseballProtocol.FailSignal failsignal = 1;</code>
     */
    public BaseballProtocol.LoginMessage.FailSignal getFailsignal() {
      return failsignal_;
    }

    private void initFields() {
      failsignal_ = BaseballProtocol.LoginMessage.FailSignal.NO_EXIST;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, failsignal_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, failsignal_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static BaseballProtocol.LoginMessage.LSC_login_result parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BaseballProtocol.LoginMessage.LSC_login_result parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BaseballProtocol.LoginMessage.LSC_login_result parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BaseballProtocol.LoginMessage.LSC_login_result parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BaseballProtocol.LoginMessage.LSC_login_result parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static BaseballProtocol.LoginMessage.LSC_login_result parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static BaseballProtocol.LoginMessage.LSC_login_result parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static BaseballProtocol.LoginMessage.LSC_login_result parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static BaseballProtocol.LoginMessage.LSC_login_result parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static BaseballProtocol.LoginMessage.LSC_login_result parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(BaseballProtocol.LoginMessage.LSC_login_result prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BaseballProtocol.LSC_login_result}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BaseballProtocol.LSC_login_result)
        BaseballProtocol.LoginMessage.LSC_login_resultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BaseballProtocol.LoginMessage.internal_static_BaseballProtocol_LSC_login_result_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BaseballProtocol.LoginMessage.internal_static_BaseballProtocol_LSC_login_result_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BaseballProtocol.LoginMessage.LSC_login_result.class, BaseballProtocol.LoginMessage.LSC_login_result.Builder.class);
      }

      // Construct using BaseballProtocol.LoginMessage.LSC_login_result.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        failsignal_ = BaseballProtocol.LoginMessage.FailSignal.NO_EXIST;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BaseballProtocol.LoginMessage.internal_static_BaseballProtocol_LSC_login_result_descriptor;
      }

      public BaseballProtocol.LoginMessage.LSC_login_result getDefaultInstanceForType() {
        return BaseballProtocol.LoginMessage.LSC_login_result.getDefaultInstance();
      }

      public BaseballProtocol.LoginMessage.LSC_login_result build() {
        BaseballProtocol.LoginMessage.LSC_login_result result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public BaseballProtocol.LoginMessage.LSC_login_result buildPartial() {
        BaseballProtocol.LoginMessage.LSC_login_result result = new BaseballProtocol.LoginMessage.LSC_login_result(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.failsignal_ = failsignal_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BaseballProtocol.LoginMessage.LSC_login_result) {
          return mergeFrom((BaseballProtocol.LoginMessage.LSC_login_result)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BaseballProtocol.LoginMessage.LSC_login_result other) {
        if (other == BaseballProtocol.LoginMessage.LSC_login_result.getDefaultInstance()) return this;
        if (other.hasFailsignal()) {
          setFailsignal(other.getFailsignal());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BaseballProtocol.LoginMessage.LSC_login_result parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BaseballProtocol.LoginMessage.LSC_login_result) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private BaseballProtocol.LoginMessage.FailSignal failsignal_ = BaseballProtocol.LoginMessage.FailSignal.NO_EXIST;
      /**
       * <code>optional .BaseballProtocol.FailSignal failsignal = 1;</code>
       */
      public boolean hasFailsignal() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .BaseballProtocol.FailSignal failsignal = 1;</code>
       */
      public BaseballProtocol.LoginMessage.FailSignal getFailsignal() {
        return failsignal_;
      }
      /**
       * <code>optional .BaseballProtocol.FailSignal failsignal = 1;</code>
       */
      public Builder setFailsignal(BaseballProtocol.LoginMessage.FailSignal value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        failsignal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .BaseballProtocol.FailSignal failsignal = 1;</code>
       */
      public Builder clearFailsignal() {
        bitField0_ = (bitField0_ & ~0x00000001);
        failsignal_ = BaseballProtocol.LoginMessage.FailSignal.NO_EXIST;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BaseballProtocol.LSC_login_result)
    }

    static {
      defaultInstance = new LSC_login_result(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BaseballProtocol.LSC_login_result)
  }

  public interface CLS_account_createOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BaseballProtocol.CLS_account_create)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional string password = 2;</code>
     */
    boolean hasPassword();
    /**
     * <code>optional string password = 2;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>optional string password = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code BaseballProtocol.CLS_account_create}
   */
  public static final class CLS_account_create extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BaseballProtocol.CLS_account_create)
      CLS_account_createOrBuilder {
    // Use CLS_account_create.newBuilder() to construct.
    private CLS_account_create(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CLS_account_create(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CLS_account_create defaultInstance;
    public static CLS_account_create getDefaultInstance() {
      return defaultInstance;
    }

    public CLS_account_create getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CLS_account_create(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              password_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BaseballProtocol.LoginMessage.internal_static_BaseballProtocol_CLS_account_create_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BaseballProtocol.LoginMessage.internal_static_BaseballProtocol_CLS_account_create_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BaseballProtocol.LoginMessage.CLS_account_create.class, BaseballProtocol.LoginMessage.CLS_account_create.Builder.class);
    }

    public static com.google.protobuf.Parser<CLS_account_create> PARSER =
        new com.google.protobuf.AbstractParser<CLS_account_create>() {
      public CLS_account_create parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CLS_account_create(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CLS_account_create> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>optional string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private java.lang.Object password_;
    /**
     * <code>optional string password = 2;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string password = 2;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string password = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = "";
      password_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswordBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswordBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static BaseballProtocol.LoginMessage.CLS_account_create parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BaseballProtocol.LoginMessage.CLS_account_create parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BaseballProtocol.LoginMessage.CLS_account_create parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BaseballProtocol.LoginMessage.CLS_account_create parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BaseballProtocol.LoginMessage.CLS_account_create parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static BaseballProtocol.LoginMessage.CLS_account_create parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static BaseballProtocol.LoginMessage.CLS_account_create parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static BaseballProtocol.LoginMessage.CLS_account_create parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static BaseballProtocol.LoginMessage.CLS_account_create parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static BaseballProtocol.LoginMessage.CLS_account_create parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(BaseballProtocol.LoginMessage.CLS_account_create prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BaseballProtocol.CLS_account_create}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BaseballProtocol.CLS_account_create)
        BaseballProtocol.LoginMessage.CLS_account_createOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BaseballProtocol.LoginMessage.internal_static_BaseballProtocol_CLS_account_create_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BaseballProtocol.LoginMessage.internal_static_BaseballProtocol_CLS_account_create_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BaseballProtocol.LoginMessage.CLS_account_create.class, BaseballProtocol.LoginMessage.CLS_account_create.Builder.class);
      }

      // Construct using BaseballProtocol.LoginMessage.CLS_account_create.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BaseballProtocol.LoginMessage.internal_static_BaseballProtocol_CLS_account_create_descriptor;
      }

      public BaseballProtocol.LoginMessage.CLS_account_create getDefaultInstanceForType() {
        return BaseballProtocol.LoginMessage.CLS_account_create.getDefaultInstance();
      }

      public BaseballProtocol.LoginMessage.CLS_account_create build() {
        BaseballProtocol.LoginMessage.CLS_account_create result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public BaseballProtocol.LoginMessage.CLS_account_create buildPartial() {
        BaseballProtocol.LoginMessage.CLS_account_create result = new BaseballProtocol.LoginMessage.CLS_account_create(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BaseballProtocol.LoginMessage.CLS_account_create) {
          return mergeFrom((BaseballProtocol.LoginMessage.CLS_account_create)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BaseballProtocol.LoginMessage.CLS_account_create other) {
        if (other == BaseballProtocol.LoginMessage.CLS_account_create.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000002;
          password_ = other.password_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BaseballProtocol.LoginMessage.CLS_account_create parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BaseballProtocol.LoginMessage.CLS_account_create) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>optional string password = 2;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            password_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BaseballProtocol.CLS_account_create)
    }

    static {
      defaultInstance = new CLS_account_create(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BaseballProtocol.CLS_account_create)
  }

  public interface LSC_account_create_resultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BaseballProtocol.LSC_account_create_result)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .BaseballProtocol.FailSignal failSignal = 1;</code>
     */
    boolean hasFailSignal();
    /**
     * <code>optional .BaseballProtocol.FailSignal failSignal = 1;</code>
     */
    BaseballProtocol.LoginMessage.FailSignal getFailSignal();
  }
  /**
   * Protobuf type {@code BaseballProtocol.LSC_account_create_result}
   */
  public static final class LSC_account_create_result extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BaseballProtocol.LSC_account_create_result)
      LSC_account_create_resultOrBuilder {
    // Use LSC_account_create_result.newBuilder() to construct.
    private LSC_account_create_result(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LSC_account_create_result(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LSC_account_create_result defaultInstance;
    public static LSC_account_create_result getDefaultInstance() {
      return defaultInstance;
    }

    public LSC_account_create_result getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LSC_account_create_result(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              BaseballProtocol.LoginMessage.FailSignal value = BaseballProtocol.LoginMessage.FailSignal.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                failSignal_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BaseballProtocol.LoginMessage.internal_static_BaseballProtocol_LSC_account_create_result_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BaseballProtocol.LoginMessage.internal_static_BaseballProtocol_LSC_account_create_result_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BaseballProtocol.LoginMessage.LSC_account_create_result.class, BaseballProtocol.LoginMessage.LSC_account_create_result.Builder.class);
    }

    public static com.google.protobuf.Parser<LSC_account_create_result> PARSER =
        new com.google.protobuf.AbstractParser<LSC_account_create_result>() {
      public LSC_account_create_result parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LSC_account_create_result(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LSC_account_create_result> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int FAILSIGNAL_FIELD_NUMBER = 1;
    private BaseballProtocol.LoginMessage.FailSignal failSignal_;
    /**
     * <code>optional .BaseballProtocol.FailSignal failSignal = 1;</code>
     */
    public boolean hasFailSignal() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .BaseballProtocol.FailSignal failSignal = 1;</code>
     */
    public BaseballProtocol.LoginMessage.FailSignal getFailSignal() {
      return failSignal_;
    }

    private void initFields() {
      failSignal_ = BaseballProtocol.LoginMessage.FailSignal.NO_EXIST;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, failSignal_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, failSignal_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static BaseballProtocol.LoginMessage.LSC_account_create_result parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BaseballProtocol.LoginMessage.LSC_account_create_result parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BaseballProtocol.LoginMessage.LSC_account_create_result parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BaseballProtocol.LoginMessage.LSC_account_create_result parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BaseballProtocol.LoginMessage.LSC_account_create_result parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static BaseballProtocol.LoginMessage.LSC_account_create_result parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static BaseballProtocol.LoginMessage.LSC_account_create_result parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static BaseballProtocol.LoginMessage.LSC_account_create_result parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static BaseballProtocol.LoginMessage.LSC_account_create_result parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static BaseballProtocol.LoginMessage.LSC_account_create_result parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(BaseballProtocol.LoginMessage.LSC_account_create_result prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BaseballProtocol.LSC_account_create_result}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BaseballProtocol.LSC_account_create_result)
        BaseballProtocol.LoginMessage.LSC_account_create_resultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BaseballProtocol.LoginMessage.internal_static_BaseballProtocol_LSC_account_create_result_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BaseballProtocol.LoginMessage.internal_static_BaseballProtocol_LSC_account_create_result_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BaseballProtocol.LoginMessage.LSC_account_create_result.class, BaseballProtocol.LoginMessage.LSC_account_create_result.Builder.class);
      }

      // Construct using BaseballProtocol.LoginMessage.LSC_account_create_result.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        failSignal_ = BaseballProtocol.LoginMessage.FailSignal.NO_EXIST;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BaseballProtocol.LoginMessage.internal_static_BaseballProtocol_LSC_account_create_result_descriptor;
      }

      public BaseballProtocol.LoginMessage.LSC_account_create_result getDefaultInstanceForType() {
        return BaseballProtocol.LoginMessage.LSC_account_create_result.getDefaultInstance();
      }

      public BaseballProtocol.LoginMessage.LSC_account_create_result build() {
        BaseballProtocol.LoginMessage.LSC_account_create_result result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public BaseballProtocol.LoginMessage.LSC_account_create_result buildPartial() {
        BaseballProtocol.LoginMessage.LSC_account_create_result result = new BaseballProtocol.LoginMessage.LSC_account_create_result(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.failSignal_ = failSignal_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BaseballProtocol.LoginMessage.LSC_account_create_result) {
          return mergeFrom((BaseballProtocol.LoginMessage.LSC_account_create_result)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BaseballProtocol.LoginMessage.LSC_account_create_result other) {
        if (other == BaseballProtocol.LoginMessage.LSC_account_create_result.getDefaultInstance()) return this;
        if (other.hasFailSignal()) {
          setFailSignal(other.getFailSignal());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BaseballProtocol.LoginMessage.LSC_account_create_result parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BaseballProtocol.LoginMessage.LSC_account_create_result) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private BaseballProtocol.LoginMessage.FailSignal failSignal_ = BaseballProtocol.LoginMessage.FailSignal.NO_EXIST;
      /**
       * <code>optional .BaseballProtocol.FailSignal failSignal = 1;</code>
       */
      public boolean hasFailSignal() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .BaseballProtocol.FailSignal failSignal = 1;</code>
       */
      public BaseballProtocol.LoginMessage.FailSignal getFailSignal() {
        return failSignal_;
      }
      /**
       * <code>optional .BaseballProtocol.FailSignal failSignal = 1;</code>
       */
      public Builder setFailSignal(BaseballProtocol.LoginMessage.FailSignal value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        failSignal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .BaseballProtocol.FailSignal failSignal = 1;</code>
       */
      public Builder clearFailSignal() {
        bitField0_ = (bitField0_ & ~0x00000001);
        failSignal_ = BaseballProtocol.LoginMessage.FailSignal.NO_EXIST;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BaseballProtocol.LSC_account_create_result)
    }

    static {
      defaultInstance = new LSC_account_create_result(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BaseballProtocol.LSC_account_create_result)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BaseballProtocol_CLS_login_request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BaseballProtocol_CLS_login_request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BaseballProtocol_LSC_login_result_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BaseballProtocol_LSC_login_result_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BaseballProtocol_CLS_account_create_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BaseballProtocol_CLS_account_create_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BaseballProtocol_LSC_account_create_result_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BaseballProtocol_LSC_account_create_result_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022LoginMessage.proto\022\020BaseballProtocol\"1" +
      "\n\021CLS_login_request\022\n\n\002id\030\001 \001(\t\022\020\n\010passw" +
      "ord\030\002 \001(\t\"D\n\020LSC_login_result\0220\n\nfailsig" +
      "nal\030\001 \001(\0162\034.BaseballProtocol.FailSignal\"" +
      "2\n\022CLS_account_create\022\n\n\002id\030\001 \001(\t\022\020\n\010pas" +
      "sword\030\002 \001(\t\"M\n\031LSC_account_create_result" +
      "\0220\n\nfailSignal\030\001 \001(\0162\034.BaseballProtocol." +
      "FailSignal*\247\001\n\nPacketType\022\025\n\021CLS_LOGIN_R" +
      "EQUEST\020\000\022\025\n\021LSC_LOGIN_SUCCESS\020\001\022\024\n\020LSC_L" +
      "OGIN_FAILED\020\002\022\026\n\022CLS_ACCOUNT_CREATE\020\003\022\036\n",
      "\032LSC_ACCOUNT_CREATE_SUCCESS\020\004\022\035\n\031LSC_ACC" +
      "OUNT_CREATE_FAILED\020\005*A\n\nFailSignal\022\014\n\010NO" +
      "_EXIST\020\000\022\021\n\rALREADY_EXIST\020\001\022\022\n\016WRONG_PAS" +
      "SWORD\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BaseballProtocol_CLS_login_request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BaseballProtocol_CLS_login_request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BaseballProtocol_CLS_login_request_descriptor,
        new java.lang.String[] { "Id", "Password", });
    internal_static_BaseballProtocol_LSC_login_result_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BaseballProtocol_LSC_login_result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BaseballProtocol_LSC_login_result_descriptor,
        new java.lang.String[] { "Failsignal", });
    internal_static_BaseballProtocol_CLS_account_create_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_BaseballProtocol_CLS_account_create_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BaseballProtocol_CLS_account_create_descriptor,
        new java.lang.String[] { "Id", "Password", });
    internal_static_BaseballProtocol_LSC_account_create_result_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_BaseballProtocol_LSC_account_create_result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BaseballProtocol_LSC_account_create_result_descriptor,
        new java.lang.String[] { "FailSignal", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
